project:
  type: website
  output-dir: docs

website:
  title: "Jess Helmer"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
      - icon: github
        href: https://github.com/jhelmer3/jhelmer3.github.io
        target: _blank
  page-footer: 
    right: This website was built with ♡ and [Quarto](https://quarto.org/){target=_blank}.

format:
  html:
    theme:
      - minty
      - styles.scss
    mainfont: Didact Gothic
    toc: true
    page-layout: full



